src/AppBundle/Entity/UserHasTaskAndSubtask.php
<?php
/**
 * Created by IntelliJ IDEA.
 * User: Kevin
 * Date: 12/03/2018
 * Time: 16:10
 */

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class User
 * @package AppBundle\Entity
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserHasTaskAndSubtaskRepository")
 * @ORM\Table(name="user_has_task_subtask")
 */
class UserHasTaskAndSubtask
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumns({
     *     @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     *     })
     */
    private $user_id;

    /**
     * @var Task
     *
     * @ORM\ManyToOne(targetEntity="Task")
     * @ORM\JoinColumns({
     *     @ORM\JoinColumn(name="task_id", referencedColumnName="id")
     *     })
     */
    private $task_id;

    /**
     * @ORM\ManyToOne(targetEntity="Subtask")
     * @ORM\JoinColumns({
     *     @ORM\JoinColumn(name="subtask_id", referencedColumnName="id")
     *     })
     */
    private $subtask_id;

    /**
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updated_at;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * @param mixed $user_id
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;
    }

    /**
     * @return mixed
     */
    public function getTaskId()
    {
        return $this->task_id;
    }

    /**
     * @param mixed $task_id
     */
    public function setTaskId($task_id)
    {
        $this->task_id = $task_id;
    }

    /**
     * @return mixed
     */
    public function getSubtaskId()
    {
        return $this->subtask_id;
    }

    /**
     * @param mixed $subtask_id
     */
    public function setSubtaskId($subtask_id)
    {
        $this->subtask_id = $subtask_id;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param mixed $created_at
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * @param mixed $updated_at
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;
    }

}

src/AppBundle/Form/UserHasTaskAndSubtaskType.php
<?php

namespace AppBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserHasTaskAndSubtaskType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user_id',EntityType::class, array(
                'placeholder' => 'Select User',
                'class' => 'AppBundle:User',
                'choice_label' => 'name',
                'attr' => ['class' => 'select2_multiple form-control'],
            ))
            ->add('task_id',EntityType::class, array(
                'placeholder' => 'Select Task',
                'class' => 'AppBundle:Task',
                'choice_label' => 'name',
                'attr' => ['class' => 'select2_multiple form-control'],
            ))
            ->add('subtask_id',EntityType::class, array(
                'placeholder' => 'Select Subtask',
                'class' => 'AppBundle:Subtask',
                'choice_label' => 'name',
                'attr' => ['class' => 'select2_multiple form-control'],
            ))
            ->add('save', SubmitType::class, array(
                'attr' => array('class' => 'btn btn-success form-control'),
            ));
    }/**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\UserHasTaskAndSubtask'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_userhastaskandsubtask';
    }


}

src/AppBundle/Controller/UserHasTaskAndSubtaskController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\UserHasTaskAndSubtask;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;use Symfony\Component\HttpFoundation\Request;

/**
 * Userhastaskandsubtask controller.
 *
 * @Route("userhastaskandsubtask")
 */
class UserHasTaskAndSubtaskController extends Controller
{
    /**
     * Lists all userHasTaskAndSubtask entities.
     *
     * @Route("/", name="userhastaskandsubtask_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $userHasTaskAndSubtasks = $em->getRepository('AppBundle:UserHasTaskAndSubtask')->findAll();

        return $this->render('@App/private/userhastaskandsubtask/list_userhastaskandsubtask.html.twig', array(
            'userHasTaskAndSubtasks' => $userHasTaskAndSubtasks,
        ));
    }

    /**
     * Creates a new userHasTaskAndSubtask entity.
     *
     * @Route("/new", name="userhastaskandsubtask_new")
     * @Method({"GET", "POST"})
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function newAction(Request $request)
    {
        $userHasTaskAndSubtask = new Userhastaskandsubtask();
        $form = $this->createForm('AppBundle\Form\UserHasTaskAndSubtaskType', $userHasTaskAndSubtask);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $userHasTaskAndSubtask->setCreatedAt(new \DateTime('now'));
            $userHasTaskAndSubtask->setUpdatedAt(new \DateTime('now'));
            $em->persist($userHasTaskAndSubtask);
            $em->flush();

            return $this->redirectToRoute('userhastaskandsubtask_index', array('id' => $userHasTaskAndSubtask->getId()));
        }

        return $this->render('@App/private/userhastaskandsubtask/create_userhastaskandsubtask.html.twig', array(
            'userHasTaskAndSubtask' => $userHasTaskAndSubtask,
            'form' => $form->createView(),
        ));
    }


    /**
     * Displays a form to edit an existing userHasTaskAndSubtask entity.
     *
     * @Route("/{id}/edit", name="userhastaskandsubtask_edit")
     * @Method({"GET", "POST"})
     * @param Request $request
     * @param UserHasTaskAndSubtask $userHasTaskAndSubtask
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, UserHasTaskAndSubtask $userHasTaskAndSubtask)
    {

        $editForm = $this->createForm('AppBundle\Form\UserHasTaskAndSubtaskType', $userHasTaskAndSubtask);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('userhastaskandsubtask_edit', array('id' => $userHasTaskAndSubtask->getId()));
        }

        return $this->render('@App/private/userhastaskandsubtask/edit_userhastaskandsubtask.html.twig', array(
            'userHasTaskAndSubtask' => $userHasTaskAndSubtask,
            'form' => $editForm->createView(),

        ));
    }

    /**
     * Deletes a userHasTaskAndSubtask entity.
     *
     * @Route("/{id}", name="userhastaskandsubtask_delete")
     * @Method("DELETE")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction(Request $request)
    {
        $userhastaskandsubtask = $this->getDoctrine()
            ->getRepository("AppBundle:UserHasTaskAndSubtask")
            ->findOneById($request->get("id"));

        var_dump($userhastaskandsubtask);
        die();

        $em = $this->getDoctrine()->getManager();
        $em->remove($userhastaskandsubtask);
        $em->flush();


        return $this->redirectToRoute('userhastaskandsubtask_index');
    }

}

src/AppBundle/Resources/views/private/userhastaskandsubtask/create_userhastaskandsubtask.html.twig
{% extends '@App/base_private.html.twig' %}
{% block body %}
    <!DOCTYPE html>
    <html lang="en">
    <body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    {{ include('@App/private/menu.html.twig') }}
                </div>
            </div>
            {{ include('@App/private/top_navigation.html.twig') }}
            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3>Assign Task/Subtask to User</h3>
                        </div>
                        <div class="title_right">
                            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                                <div class="input-group">
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="x_panel">
                                    <div class="x_content">
                                        {{ form_start(form) }}
                                        <div class="col-md-4 col-sm-6 col-xs-12 form-group has-feedback ">
                                            {{ form_label(form.user_id,"User") }}
                                            {{ form_widget(form.user_id) }}
                                            {{ form_errors(form.user_id) }}
                                        </div>
                                        <div class="col-md-4 col-sm-6 col-xs-12 ">
                                            {{ form_label(form.task_id,"Task") }}
                                            {{ form_widget(form.task_id) }}
                                            {{ form_errors(form.task_id) }}
                                        </div>
                                        <div class="col-md-4 col-sm-6 col-xs-12 ">
                                            {{ form_label(form.subtask_id,"SubTask") }}
                                            {{ form_widget(form.subtask_id) }}
                                            {{ form_errors(form.subtask_id) }}
                                        </div>
                                        <div class="clearfix"></div>
                                        <br>
                                        <div class="col-md-1 col-sm-6 col-xs-12 pull-right">
                                            {{ form_widget(form.save) }}
                                        </div>
                                        <div class="clearfix"></div>
                                        {{ form_end(form) }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <footer>
        <div class="pull-right">
            Gestor de Projectes - All rights are reserved by <b>Kevin Garcia</b> & <b>Nestor Ibañez</b>
        </div>
        <div class="clearfix"></div>
    </footer>
    <!-- /footer content -->

    <!-- jQuery -->
    <script src="{{ asset('vendor/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ asset('vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('vendor/fastclick/lib/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script src="{{ asset('vendor/nprogress/nprogress.js') }}"></script>
    <!-- iCheck -->
    <script src="{{ asset('vendor/iCheck/icheck.min.js') }}"></script>
    <!-- Datatables -->
    <script src="{{ asset('vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
    <script src="{{ asset('vendor/jszip/dist/jszip.min.js') }}"></script>
    <script src="{{ asset('vendor/pdfmake/build/pdfmake.min.js') }}"></script>
    <script src="{{ asset('vendor/pdfmake/build/vfs_fonts.js') }}"></script>
    {#<script src="{{ asset('vendor/bootstrap-notify/bootstrap-notify.min.js') }}"></script>#}
    {#<script src="{{ asset('vendor/bootstrap-growl-master/jquery.bootstrap-growl.min.js') }}"></script>#}

    <!-- Custom Theme Scripts -->
    <script src="{{ asset('js/custom.min.js') }}"></script>

    </body>
    </html>

{% endblock %}

src/AppBundle/Resources/views/private/userhastaskandsubtask/edit_userhastaskandsubtask.html.twig
{% extends '@App/base_private.html.twig' %}
{% block body %}
    <!DOCTYPE html>
    <html lang="en">
    <body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    {{ include('@App/private/menu.html.twig') }}
                </div>
            </div>
            {{ include('@App/private/top_navigation.html.twig') }}
            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3>Assign Task/Subtask to User</h3>
                        </div>
                        <div class="title_right">
                            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                                <div class="input-group">
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="x_panel">
                                    <div class="x_content">
                                        {{ form_start(form) }}
                                        <div class="col-md-4 col-sm-6 col-xs-12 form-group has-feedback ">
                                            {{ form_label(form.user_id,"User") }}
                                            {{ form_widget(form.user_id) }}
                                            {{ form_errors(form.user_id) }}
                                        </div>
                                        <div class="col-md-4 col-sm-6 col-xs-12 ">
                                            {{ form_label(form.task_id,"Task") }}
                                            {{ form_widget(form.task_id) }}
                                            {{ form_errors(form.task_id) }}
                                        </div>
                                        <div class="col-md-4 col-sm-6 col-xs-12 ">
                                            {{ form_label(form.subtask_id,"SubTask") }}
                                            {{ form_widget(form.subtask_id) }}
                                            {{ form_errors(form.subtask_id) }}
                                        </div>
                                        <div class="clearfix"></div>
                                        <br>
                                        <div class="col-md-1 col-sm-6 col-xs-12 pull-right">
                                            {{ form_widget(form.save) }}
                                        </div>
                                        <div class="clearfix"></div>
                                        {{ form_end(form) }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <footer>
        <div class="pull-right">
            Gestor de Projectes - All rights are reserved by <b>Kevin Garcia</b> & <b>Nestor Ibañez</b>
        </div>
        <div class="clearfix"></div>
    </footer>
    <!-- /footer content -->

    <!-- jQuery -->
    <script src="{{ asset('vendor/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ asset('vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('vendor/fastclick/lib/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script src="{{ asset('vendor/nprogress/nprogress.js') }}"></script>
    <!-- iCheck -->
    <script src="{{ asset('vendor/iCheck/icheck.min.js') }}"></script>
    <!-- Datatables -->
    <script src="{{ asset('vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
    <script src="{{ asset('vendor/jszip/dist/jszip.min.js') }}"></script>
    <script src="{{ asset('vendor/pdfmake/build/pdfmake.min.js') }}"></script>
    <script src="{{ asset('vendor/pdfmake/build/vfs_fonts.js') }}"></script>
    {#<script src="{{ asset('vendor/bootstrap-notify/bootstrap-notify.min.js') }}"></script>#}
    {#<script src="{{ asset('vendor/bootstrap-growl-master/jquery.bootstrap-growl.min.js') }}"></script>#}

    <!-- Custom Theme Scripts -->
    <script src="{{ asset('js/custom.min.js') }}"></script>

    </body>
    </html>

{% endblock %}

src/AppBundle/Resources/views/private/userhastaskandsubtask/list_userhastaskandsubtask.html.twig
{% extends '@App/base_private.html.twig' %}
{% block body %}
    <!DOCTYPE html>
    <html lang="en">
    <body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    {{ include('@App/private/menu.html.twig') }}
                </div>
            </div>
            {{ include('@App/private/top_navigation.html.twig') }}
            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3>List of Task/Subtask assigned to Users</h3>
                        </div>
                        <div class="title_right">
                            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                                <div class="input-group">
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>

                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <table id="datatable" class="table table-striped table-bordered">
                                            <thead>
                                            <tr>
                                                <th>Id</th>
                                                <th>User</th>
                                                <th>Task</th>
                                                <th>Subtask</th>
                                                <th class="col-md-2">Actions</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for aux in userHasTaskAndSubtasks %}
                                                <tr>
                                                    <td>{{ aux.id }} </td>
                                                    <td>{{ aux.userId.name }}</td>
                                                    <td>{{ aux.taskId.name }}</td>
                                                    <td>{{ aux.subtaskId.name }}</td>
                                                    <td style=" padding: 5px 5px 5px 5px;">
                                                        <div class="col-md-12">
                                                            <button type="submit" class=" button_edit"><a style="text-decoration: none;color: #ffffff;" href="{{ path('userhastaskandsubtask_edit',{'id': aux.id })}}">Edit</a></button>
                                                            {#<button type="button" class="col-md-6 col-md-push-1 button_delete" data-toggle="modal" data-backdrop="static" data-keyboard="false" data-target="#myModal"  data-client-id-url="{{ path('user_delete',{'id': user.id })}}">Delete</button>#}
                                                        </div>

                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->

    <!--modal-->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Delete User</h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete user permantly?</p>
                </div>
                <div class="modal-footer text-right">
                    <button style="float: right;" type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <form style="float: right;" id="formConfirmDelete" action="">
                        <button  type="submit" class="btn btn-primary" id="confirmButton">Yes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--/modal-->


    <!-- footer content -->
    <footer>
        <div class="pull-right">
            Gestor de Projectes - All rights are reserved by <b>Kevin Garcia</b> & <b>Nestor Ibañez</b>
        </div>
        <div class="clearfix"></div>
    </footer>
    <!-- /footer content -->

    <!-- jQuery -->
    <script src="{{ asset('vendor/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ asset('vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('vendor/fastclick/lib/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script src="{{ asset('vendor/nprogress/nprogress.js') }}"></script>
    <!-- iCheck -->
    <script src="{{ asset('vendor/iCheck/icheck.min.js') }}"></script>
    <!-- Datatables -->
    <script src="{{ asset('vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
    <script src="{{ asset('vendor/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
    <script src="{{ asset('vendor/jszip/dist/jszip.min.js') }}"></script>
    <script src="{{ asset('vendor/pdfmake/build/pdfmake.min.js') }}"></script>
    <script src="{{ asset('vendor/pdfmake/build/vfs_fonts.js') }}"></script>
    {#<script src="{{ asset('vendor/bootstrap-notify/bootstrap-notify.min.js') }}"></script>#}
    {#<script src="{{ asset('vendor/bootstrap-growl-master/jquery.bootstrap-growl.min.js') }}"></script>#}

    <!-- Custom Theme Scripts -->
    <script src="{{ asset('js/custom.min.js') }}"></script>

    </body>
    </html>

{% endblock %}